version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: challenge_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: challenge_db
    ports:
      - "25432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: challenge_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_NAME: challenge_db
      DB_PASSWORD: 123456
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: